version: '2'

services:
  app:
    build: .
    environment:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'SEARCH_API_KEY=${SEARCH_API_KEY}'
      - 'SEARCH_APP_ID=${SEARCH_APP_ID}'
      - 'PORT=80'
      - 'STATIC_PWD=/srv'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/srv/${CREDENTIALS}'
      - 'GRPC_GO_LOG_SEVERITY_LEVEL=INFO'
    ports:
      - '80:80'
    volumes:
      - './:/srv'
      - '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt'
